name: Deploy Firebase App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}

    steps:
      - name: ğŸ”„ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ§° Instalar dependÃªncias
        run: |
          npm install -g firebase-tools

      - name: ğŸ—ï¸ Criar arquivo de credencial temporÃ¡rio
        run: |
          mkdir -p firebase-admin
          echo "$FIREBASE_KEY" > firebase-admin/serviceAccountKey.json

      - name: ğŸ” Autenticar no Firebase
        run: |
          firebase auth:login:ci --token "$(firebase login:ci)"
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-admin/serviceAccountKey.json

      - name: ğŸš€ Deploy para Firebase
        run: |
          firebase deploy --only hosting